CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firts__name" varchar NOT NULL,
  "last__name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "password" varchar NOT NULL,
  "birthday" date NOT NULL,
  "phone" varchar DEFAULT '+12 123456'
);

CREATE TABLE "title" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courses" varchar NOT NULL,
  "id__user" int NOT NULL,
  "description" text NOT NULL,
  "level" int NOT NULL,
  "teacher" varchar NOT NULL
);

CREATE TABLE "courses__videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id__title" int NOT NULL,
  "id__title__catgories" int NOT NULL,
  "title" varchar,
  "url" varchar,
  "password" varchar NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "title__categorias" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id__title" int,
  "id__categories" int
);

ALTER TABLE "title" ADD FOREIGN KEY ("id__user") REFERENCES "users" ("id");

ALTER TABLE "title__categorias" ADD FOREIGN KEY ("id__title") REFERENCES "title" ("id");

ALTER TABLE "title__categorias" ADD FOREIGN KEY ("id__categories") REFERENCES "categories" ("id");

ALTER TABLE "courses__videos" ADD FOREIGN KEY ("id__title__catgories") REFERENCES "title__categorias" ("id");

-- ADDING TO USERS

insert  into users (
firts__name,
last__name, 
email,
"password", 
birthday, 
phone
) values (
'Luis',
'Jojoa', 
'luisjojoa@academlo.com', 
'123ds',
'12/11/2000',
'5723456' ),(
'Camilo',
'Loasada', 
'CL@academlo.com', 
'123es',
'22/12/2000',
'572343');

--ADDING TITLE OF COURSE



insert into title (
courses,
id__user,
description,
"level",
teacher
) values (
'fundamentos',
1,
'En  este curso aprenderas de manera practica y muy didáctica los fundamentos de HTML, CSS Y JAVASCRIPT',
1,
'Jesus' 
),(
'React',
2,
'En  este curso te formaras en habilidades de Frontend',
2,
'Camilo' 
)


--ADDING COURSES VIDEOS

insert into courses__videos (
id__title__catgories,
title,
url) values (
1, 'Notions of HTML', 
'https//qwjenqwjne22');
